// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PainelContabil.Repository;

namespace PainelContabil.Repository.Migrations
{
    [DbContext(typeof(PainelContabilContext))]
    [Migration("20210201042619_balancodia")]
    partial class balancodia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PainelContabil.Domain.BalancoDia", b =>
                {
                    b.Property<DateTime>("DataBalanco")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Saldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ValorTotalCredito")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ValorTotalDebito")
                        .HasColumnType("decimal(18,4)");

                    b.ToTable("BalancosDias");
                });

            modelBuilder.Entity("PainelContabil.Domain.LancamentoFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("LancamentosFinanceiros");
                });
#pragma warning restore 612, 618
        }
    }
}
